In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [2]:
# Loading the dataset
fake = pd.read_csv("data/Fake.csv")
real = pd.read_csv("data/True.csv")

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
real.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake.shape

(23481, 4)

In [6]:
real.shape

(21417, 4)

In [7]:
fake['Fake'] = np.ones(fake.shape[0])
real['Fake'] = np.zeros(real.shape[0])

In [8]:
combined_news = pd.concat([fake,real])

In [9]:
combined_news

,title,text,subject,date,Fake
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1.0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1.0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1.0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1.0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1.0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0.0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0.0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0.0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0.0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0.0

In [10]:
news = combined_news.sample(n = combined_news.shape[0],random_state = 4)

In [11]:
news.shape

(44898, 5)

In [12]:
news.reset_index(inplace = True)

In [13]:
news.drop(labels = 'index',axis =1,inplace = True)

In [14]:
news.head()

,title,text,subject,date,Fake
0,Virginia Trump Supporter Patrols Polling Plac...,"A Trump supporter in Loudoun County, Virginia,...",News,"November 5, 2016",1.0
1,"Senate to act this week on Obamacare repeal, M...",WASHINGTON (Reuters) - The U.S. Senate will ta...,politicsNews,"January 8, 2017",0.0
2,Online ads offer legal option for U.S. electio...,SAN FRANCISCO (Reuters) - The laws that prohib...,politicsNews,"July 13, 2017",0.0
3,Hustler Owner Is So Fed Up With Trump That He...,Donald Trump is a danger to the nation and the...,News,"October 14, 2017",1.0
4,"Trump would freeze new federal regulations, re...",WASHINGTON (Reuters) - Republican presidential...,politicsNews,"August 8, 2016",0.0

## Data Exploration

In [15]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
Fake       0
dtype: int64

In [16]:
news['date'].dtype

dtype('O')

In [17]:
print (datetime.now().strftime('%d %B %y '))

01 February 23

In [18]:
news['date']

0        November 5, 2016
1        January 8, 2017
2          July 13, 2017
3        October 14, 2017
4         August 8, 2016
               ...
44893        May 20, 2016
44894        Jan 19, 2017
44895       May 25, 2017
44896    February 2, 2016
44897        Dec 12, 2017
Name: date, Length: 44898, dtype: object

In [19]:
def string_to_time(string):
    try:
        try:
            return datetime.strptime(string.strip(),'%B %d, %Y')
        except:
            return datetime.strptime(string.strip(),'%b %d, %Y')
    except:
        try:
            return datetime.strptime(string.strip(),'%d-%b-%y')
        except:
            return string

news['date'] = news['date'].apply(string_to_time)

In [20]:
news.head()

,title,text,subject,date,Fake
0,Virginia Trump Supporter Patrols Polling Plac...,"A Trump supporter in Loudoun County, Virginia,...",News,2016-11-05 00:00:00,1.0
1,"Senate to act this week on Obamacare repeal, M...",WASHINGTON (Reuters) - The U.S. Senate will ta...,politicsNews,2017-01-08 00:00:00,0.0
2,Online ads offer legal option for U.S. electio...,SAN FRANCISCO (Reuters) - The laws that prohib...,politicsNews,2017-07-13 00:00:00,0.0
3,Hustler Owner Is So Fed Up With Trump That He...,Donald Trump is a danger to the nation and the...,News,2017-10-14 00:00:00,1.0
4,"Trump would freeze new federal regulations, re...",WASHINGTON (Reuters) - Republican presidential...,politicsNews,2016-08-08 00:00:00,0.0

In [21]:
string_indexes = []
for i in range(news.shape[0]):
    if (type(news['date'][i])==str):
        print (news['date'][i])
        string_indexes.append(i)

https://100percentfedup.com/12-yr-old-black-conservative-whose-video-to-obama-went-viral-do-you-really-love-america-receives-death-threats-from-left/
https://100percentfedup.com/video-hillary-asked-about-trump-i-just-want-to-eat-some-pie/
https://fedup.wpengine.com/wp-content/uploads/2015/04/hillarystreetart.jpg
https://100percentfedup.com/served-roy-moore-vietnamletter-veteran-sets-record-straight-honorable-decent-respectable-patriotic-commander-soldier/
MSNBC HOST Rudely Assumes Steel Worker Would Never Let His Son Follow in His Footsteps…He Couldn’t Be More Wrong [Video]
https://fedup.wpengine.com/wp-content/uploads/2015/04/hillarystreetart.jpg
https://fedup.wpengine.com/wp-content/uploads/2015/04/entitled.jpg
https://fedup.wpengine.com/wp-content/uploads/2015/04/entitled.jpg
https://fedup.wpengine.com/wp-content/uploads/2015/04/entitled.jpg
https://fedup.wpengine.com/wp-content/uploads/2015/04/hillarystreetart.jpg

In [22]:
news.drop(index = string_indexes,axis =0 ,inplace = True)

In [23]:
news.shape

(44888, 5)

In [24]:
news['subject'].value_counts()

politicsNews       11272
worldnews          10145
News                9050
politics            6836
left-news           4456
Government News     1568
US_News              783
Middle-east          778
Name: subject, dtype: int64

In [28]:
news_subjects = pd.get_dummies(news,columns = ['subject'])

In [30]:
news_subjects

,title,text,date,Fake,subject_Government News,subject_Middle-east,subject_News,subject_US_News,subject_left-news,subject_politics,subject_politicsNews,subject_worldnews
0,Virginia Trump Supporter Patrols Polling Plac...,"A Trump supporter in Loudoun County, Virginia,...",2016-11-05 00:00:00,1.0,0,0,1,0,0,0,0,0
1,"Senate to act this week on Obamacare repeal, M...",WASHINGTON (Reuters) - The U.S. Senate will ta...,2017-01-08 00:00:00,0.0,0,0,0,0,0,0,1,0
2,Online ads offer legal option for U.S. electio...,SAN FRANCISCO (Reuters) - The laws that prohib...,2017-07-13 00:00:00,0.0,0,0,0,0,0,0,1,0
3,Hustler Owner Is So Fed Up With Trump That He...,Donald Trump is a danger to the nation and the...,2017-10-14 00:00:00,1.0,0,0,1,0,0,0,0,0
4,"Trump would freeze new federal regulations, re...",WASHINGTON (Reuters) - Republican presidential...,2016-08-08 00:00:00,0.0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
44893,Snowden Laughs-off CIA Excuse of ‘Mistakenly D...,21st Century Wire says This week s announcemen...,2016-05-20 00:00:00,1.0,0,1,0,0,0,0,0,0
44894,WATCH MAJOR MOMENT President-elect Trump And E...,,2017-01-19 00:00:00,1.0,0,0,0,0,0,1,0,0
44895,Republican congressional candidate in Montana ...,(Reuters) - Montana Republican congressional c...,2017-05-25 00:00:00,0.0,0,0,0,0,0,0,1,0
44896,Nazi-Ranting Man Accosts MSNBC Host At Iowa C...,A man ranting about Nazi Germany had a strange...,2016-02-02 00:00:00,1.0,0,0,1,0,0,0,0,0
44897,WATCH: ESTABLISHMENT REPUBLICAN Pollster Tries...,Establishment Republican pollster Frank Luntz ...,2017-12-12 00:00:00,1.0,0,0,0,0,1,0,0,0