In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Loading the dataset
fake = pd.read_csv("data/Fake.csv")
real = pd.read_csv("data/True.csv")

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
real.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
fake.shape

(23481, 4)

In [6]:
real.shape

(21417, 4)

In [7]:
fake['Fake'] = np.ones(fake.shape[0])
real['Fake'] = np.zeros(real.shape[0])

In [14]:
combined_news = pd.concat([fake,real])

In [15]:
combined_news

,title,text,subject,date,Fake
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",1.0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",1.0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",1.0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",1.0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",1.0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0.0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0.0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0.0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0.0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0.0

In [16]:
news = combined_news.sample(n = combined_news.shape[0],random_state = 4)

In [17]:
news.head()

,title,text,subject,date,Fake
3933,Virginia Trump Supporter Patrols Polling Plac...,"A Trump supporter in Loudoun County, Virginia,...",News,"November 5, 2016",1.0
6461,"Senate to act this week on Obamacare repeal, M...",WASHINGTON (Reuters) - The U.S. Senate will ta...,politicsNews,"January 8, 2017",0.0
2789,Online ads offer legal option for U.S. electio...,SAN FRANCISCO (Reuters) - The laws that prohib...,politicsNews,"July 13, 2017",0.0
223,Hustler Owner Is So Fed Up With Trump That He...,Donald Trump is a danger to the nation and the...,News,"October 14, 2017",1.0
8518,"Trump would freeze new federal regulations, re...",WASHINGTON (Reuters) - Republican presidential...,politicsNews,"August 8, 2016",0.0

In [19]:
news.reset_index(inplace = True)

In [20]:
news.drop(labels = 'index',axis =1,inplace = True)

In [22]:
news.head()

,title,text,subject,date,Fake
0,Virginia Trump Supporter Patrols Polling Plac...,"A Trump supporter in Loudoun County, Virginia,...",News,"November 5, 2016",1.0
1,"Senate to act this week on Obamacare repeal, M...",WASHINGTON (Reuters) - The U.S. Senate will ta...,politicsNews,"January 8, 2017",0.0
2,Online ads offer legal option for U.S. electio...,SAN FRANCISCO (Reuters) - The laws that prohib...,politicsNews,"July 13, 2017",0.0
3,Hustler Owner Is So Fed Up With Trump That He...,Donald Trump is a danger to the nation and the...,News,"October 14, 2017",1.0
4,"Trump would freeze new federal regulations, re...",WASHINGTON (Reuters) - Republican presidential...,politicsNews,"August 8, 2016",0.0